In [3]:
import cv2
import numpy as np
import pandas as pd

In [5]:
 img = cv2.imread(r"C:\Users\91912\Downloads\flower_photos\tulips\38287568_627de6ca20.jpg")

In [7]:
img.shape

(333, 500, 3)

#### 1)Translation

In [43]:
# Translation matrix
tx = 50
ty = 50
t_m = np.array([[1,0,tx],[0,1,ty]],dtype = np.float32)

In [45]:
t_m

array([[ 1.,  0., 50.],
       [ 0.,  1., 50.]], dtype=float32)

In [49]:
# image translation
t_img = cv2.warpAffine(img,t_m,(500,333))

In [51]:
cv2.imshow("Orginal",img)
cv2.imshow("Translated_img",t_img)
cv2.waitKey()
cv2.destroyAllWindows()

##### Image translation along with borderMode

In [62]:
t_img1 = cv2.warpAffine(img,t_m,(500,333),borderMode = cv2.BORDER_REFLECT)
t_img2 = cv2.warpAffine(img,t_m,(500,333),borderMode = cv2.BORDER_CONSTANT,borderValue = (50,155,255))

In [64]:
cv2.imshow("Orginal",img)
cv2.imshow("Translated_img1",t_img1)
cv2.imshow("Translated_img2",t_img2)
cv2.waitKey()
cv2.destroyAllWindows()

#### 2) Rotation

In [70]:
img.shape

(333, 500, 3)

In [82]:
r_m = cv2.getRotationMatrix2D((166,225),90,1) # 1 is used for without Zooming
r_m1 = cv2.getRotationMatrix2D((166,225),60,1)
r_m2 = cv2.getRotationMatrix2D((166,225),45,1)
r_m3 = cv2.getRotationMatrix2D((166,225),30,1)

In [74]:
r_m

array([[ 6.123234e-17,  1.000000e+00, -5.900000e+01],
       [-1.000000e+00,  6.123234e-17,  3.910000e+02]])

In [84]:
r_img = cv2.warpAffine(img,r_m,(500,333))
r_img1 = cv2.warpAffine(img,r_m1,(500,333))
r_img2 = cv2.warpAffine(img,r_m2,(500,333))
r_img3 = cv2.warpAffine(img,r_m3,(500,333))

In [86]:
cv2.imshow("Orginal",img)
cv2.imshow("Rotated_img",r_img)
cv2.imshow("Rotated_img1",r_img1)
cv2.imshow("Rotated_img2",r_img2)
cv2.imshow("Rotated_img3",r_img3)
cv2.waitKey()
cv2.destroyAllWindows()

In [115]:
r_m0 = cv2.getRotationMatrix2D((0,0),45,1)

In [117]:
r_img0 = cv2.warpAffine(img,r_m0,(500,333))

In [119]:
cv2.imshow("Rotated_img0",r_img0)
cv2.waitKey()
cv2.destroyAllWindows()

##### Rotate

In [107]:
img1 = cv2.rotate(img,cv2.ROTATE_180)
img2 = cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)
img3 = cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISE)

cv2.imshow("Orginal",img)
cv2.imshow("Rotated_img1",img1)
cv2.imshow("Rotated_img2",img2)
cv2.imshow("Rotated_img3",img3)
cv2.waitKey()
cv2.destroyAllWindows()

#### 3) Scaling

In [140]:
sx = 3
sy = 3
tx = 0
ty = 0
sc_m = np.array([[sx,0,tx],[0,sy,ty]],dtype = np.float32)

In [142]:
sc_m

array([[3., 0., 0.],
       [0., 3., 0.]], dtype=float32)

In [144]:
scale_img = cv2.warpAffine(img,sc_m,(500,333))

In [146]:
cv2.imshow("Orginal_img",img)
cv2.imshow("Zoomed_img",scale_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [150]:
cv2.imshow("Orginal_img",cv2.resize(img,(500,500)))
cv2.imshow("Zoomed_img",cv2.resize(img,(50,50)))
cv2.waitKey()
cv2.destroyAllWindows()

#### 4) Sheering

In [160]:
shx = 1
shy = 0
tx = 0
ty = 0
sh_m = np.array([[1,shx,tx],[shy,1,ty]],dtype = np.float32)

In [170]:
she_img = cv2.warpAffine(img,sh_m,(500,333))

In [172]:
cv2.imshow("Orginal_img",img)
cv2.imshow("Sheering_img",she_img)
cv2.waitKey()
cv2.destroyAllWindows()

#### 5) Cropping

In [176]:
img.shape

(333, 500, 3)

In [187]:
cr_img = img[70:150,155:250]

In [ ]:
cv2.imshow("Orginal_img",img)
cv2.imshow("Croped_img",cr_img)
cv2.waitKey()
cv2.destroyAllWindows()